<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{
    public function run()
    {
        $users =
        [
        	[// 1
                'email'             => 'nami@gmail.com',
                'password'          => bcrypt('nami'),
                'uFirstname'        => 'Nami',
                'uMiddlename'       => 'Bermudo',
                'uLastname'         => 'Lao Cubelo',
                'uBirthday'         => '1997-07-13',
                'uGender'           => 'Female',
                'uLivingStatus'     => 'Living',
                'uMaritalStatus'    => 'Single',
            ],
            [// 2
                'email'             => 'nora@gmail.com',
                'password'          => bcrypt('nora'),
                'uFirstname'        => 'Nora',
                'uMiddlename'       => 'Bermudo',
                'uLastname'         => 'Lao Cubelo',
                'uBirthday'         => '1970-12-06',
                'uGender'           => 'Female',
                'uLivingStatus'     => 'Living',
                'uMaritalStatus'    => 'Married',
            ],
            [// 3
                'email'             => 'rene@gmail.com',
                'password'          => bcrypt('rene'),
                'uFirstname'        => 'Rene',
                'uMiddlename'       => 'Cloribel',
                'uLastname'         => 'Lao Cubelo',
                'uBirthday'         => '1970-02-21',
                'uGender'           => 'Male',
                'uLivingStatus'     => 'Living',
                'uMaritalStatus'    => 'Married',
            ],
            [// 4
                'email'             => 'dave@gmail.com',
                'password'          => bcrypt('dave'),
                'uFirstname'        => 'Dave',
                'uMiddlename'       => 'Flores',
                'uLastname'         => 'Baclayon',
                'uBirthday'         => '1990-03-12',
                'uGender'           => 'Male',
                'uLivingStatus'     => 'Living',
                'uMaritalStatus'    => 'Married',
            ],
            [// 5
                'email'             => 'hinata@gmail.com',
                'password'          => bcrypt('hinata'),
                'uFirstname'        => 'Hinata',
                'uMiddlename'       => '',
                'uLastname'         => 'Shoyo',
                'uBirthday'         => '1996-06-21',
                'uGender'           => 'Male',
                'uLivingStatus'     => 'Living',
                'uMaritalStatus'    => 'Single',
            ],
            [// 6
                'email'             => 'gio@gmail.com',
                'password'          => bcrypt('gio'),
                'uFirstname'        => 'Gio',
                'uMiddlename'       => '',
                'uLastname'         => 'Conridge',
                'uBirthday'         => '1988-07-25',
                'uGender'           => 'Male',
                'uLivingStatus'     => 'Living',
                'uMaritalStatus'    => 'Single',
            ],
            [// 7
                'email'             => 'carlo@gmail.com',
                'password'          => bcrypt('carlo'),
                'uFirstname'        => 'Carlo',
                'uMiddlename'       => 'Ridge',
                'uLastname'         => 'Villacin',
                'uBirthday'         => '1989-08-19',
                'uGender'           => 'Male',
                'uLivingStatus'     => 'Living',
                'uMaritalStatus'    => 'Married',
            ],
            [// 8
                'email'             => 'Sir@gmail.com',
                'password'          => bcrypt('123456'),
                'uFirstname'        => 'Roderick',
                'uMiddlename'       => 'Agravante',
                'uLastname'         => 'Bandalan',
                'uBirthday'         => '1964-05-20',
                'uGender'           => 'Male',
                'uLivingStatus'     => 'Living',
                'uMaritalStatus'    => 'Married',
            ],
            [// 9
                 'email'            => 'mam@gmail.com',
                 'password'         => bcrypt('123456'),
                 'uFirstname'       => 'Marissa',
                 'uMiddlename'      => 'Mahilum',
                 'uLastname'        => 'Boctuanon',
                 'uBirthday'        => '1978-10-30',
                 'uGender'          => 'Female',
                 'uLivingStatus'    => 'Living',
                 'uMaritalStatus'   => 'Single',
            ],
            [// 10
                'email'             => 'Amanda@gmail.com',
                'password'          => bcrypt('123456'),
                'uFirstname'        => 'Amanda',
                'uMiddlename'       => 'Poppins',
                'uLastname'         => 'Cerny',
                'uBirthday'         => '1982-12-22',
                'uGender'           => 'Female',
                'uLivingStatus'     => 'Living',
                'uMaritalStatus'    => 'Married',
            ],
            [// 11
                'email'             => 'kathleen@gmail.com',
                'password'          => bcrypt('123456'),
                'uFirstname'        => 'Kathleen cai',
                'uMiddlename'       => 'So',
                'uLastname'         => 'De Guzman',
                'uBirthday'         => '1965-06-20',
                'uGender'           => 'Female',
                'uLivingStatus'     => 'Living',
                'uMaritalStatus'    => 'Single',
            ],
            [// 12
                'email'             => 'allen@gmail.com',
                'password'          => bcrypt('allen'),
                'uFirstname'        => 'Allen Dale',
                'uMiddlename'       => 'Verina',
                'uLastname'         => 'Gabisan',
                'uBirthday'         => '1996-11-10',
                'uGender'           => 'Male',
                'uLivingStatus'     => 'Living',
                'uMaritalStatus'    => 'Married',
            ],
            [// 13
                'email'             => 'shanyl@gmail.com',
                'password'          => bcrypt('shanyl'),
                'uFirstname'        => 'Shanyl',
                'uMiddlename'       => 'Jimenez',
                'uLastname'         => 'Chiong',
                'uBirthday'         => '1995-01-30',
                'uGender'           => 'Female',
                'uLivingStatus'     => 'Living',
                'uMaritalStatus'    => 'Married',
            ],
            [// 14
                'email'             => 'gigi@gmail.com',
                'password'          => bcrypt('gigi'),
                'uFirstname'        => 'Cynthia',
                'uMiddlename'       => 'Vilan',
                'uLastname'         => 'Verina',
                'uBirthday'         => '1966-09-06',
                'uGender'           => 'Female',
                'uLivingStatus'     => 'Living',
                'uMaritalStatus'    => 'Single',
            ],
            [// 15
                'email'             => 'gina@gmail.com',
                'password'          => bcrypt('gina'),
                'uFirstname'        => 'Gina',
                'uMiddlename'       => 'Ella',
                'uLastname'         => 'Lopez',
                'uBirthday'         => '1961-11-06',
                'uGender'           => 'Female',
                'uLivingStatus'     => 'Living',
                'uMaritalStatus'    => 'Single',
            ],

        ];

        DB::table('users')->insert($users);
    }
}
